version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  bun-vite-test:
    docker:
      - image: oven/bun:latest
    steps:
      - checkout
      - run:
          name: "bun-vite-test"
          command: bun test
  bun-vite-build:
    docker:
      - image: oven/bun:latest
    steps:
      - checkout
      - run: bun add typescript
      - run: bun run build
      - store_artifacts:
          path: dist
          destination: /tmp/template-vite-react-swc-ts
workflows:
  test-and-build:
    jobs:
      - bun-vite-test
      - bun-vite-build:
          requires:
            - bun-vite-test
